version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.6.0

jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Image
          command: docker build -t appvia/atlassian-jira-service-desk:$CIRCLE_SHA1 .
      - anchore/analyze_local_image:
          image_name: appvia/atlassian-jira-service-desk:$CIRCLE_SHA1
          policy_failure: true

  push_latest:
    machine: true
    steps:
      - checkout
      - run:
          name: Push to Quay with tag latest
          command: |
            docker build -t quay.io/appvia/atlassian-jira-service-desk:latest .
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/atlassian-jira-service-desk:latest

  push_tag:
    machine: true
    steps:
      - checkout
      - run:
          name: Push to Quay with Git tag
          command: |
            docker build -t quay.io/appvia/atlassian-jira-service-desk:$CIRCLE_TAG .
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/atlassian-jira-service-desk:$CIRCLE_TAG

workflows:
  version: 2.1
  run_build:
    jobs:
      - local_image_scan
      - push_latest:
          requires:
            - local_image_scan
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
      - push_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
